version: '3.9'

services:
  gitlab:
    # build: ./gitlab
    image: shukridozom/gitlab-server:1.0.0
    container_name: gitlab-server
    restart: always
    ports:
      - "${GITLAB_PORT}:80"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_shared_data:/shared
    networks:
      - ${GITLAB_NET}
    shm_size: '256m'

  gitlab-runner:
    # build: ./gitlab-runner
    image: shukridozom/gitlab-agent:1.0.0
    privileged: true
    container_name: gitlab-agent
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_shared_data:/shared
    environment:
      GITLAB_NET: ${GITLAB_NET}
    networks:
      - ${GITLAB_NET}

networks:
  gitlabnet:
    name: ${GITLAB_NET}
    driver: bridge

volumes:
  gitlab_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GITLAB_VOL_CONFIG_PATH}

  gitlab_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GITLAB_VOL_LOGS_PATH}
      
  gitlab_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GITLAB_VOL_DATA_PATH}

  gitlab_shared_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GITLAB_VOL_SHARED_DATA_PATH}
